name: CI
run-name: ${{ github.actor }}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Build
        uses: threeal/cmake-action@v2.0.0
        with:
          build-dir: build
      - name: Run tests
        run: ls
      - run: find . -type f -wholename "./tests/test_*" -executable -exec {} \;
