name: CI
run-name: ${{ github.actor }}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Build
        uses: threeal/cmake-action@v2.0.0
        with:
          build-dir: build

      - name: Allow script execution
        run: chmod +x ./scripts/run_tests.sh

      - name: Run tests
        run: find . -type f -wholename "./build/tests/test_*" -executable | ./scripts/run_tests.sh
